### ISSUE TITLE
Loses connection with HA.

### ISSUE THREAD

**Issue by adamjrbaker** [schmic/Loupedeck-HomeAssistant#8] opened 2024-03-20 15:23 UTC
Hello, 

Looks like loopdeck loses connection with HA when my computer goes to sleep overnight. The solve is to restart the loopdeck application/device and everything works again. 

Not sure if you have had this issue. 

- Adam B.

**Comment by adamjrbaker** [comment] 2024-05-10 03:12
Hey @schmic any update on this bug fix?

**Comment by schmic** [comment] 2024-05-10 12:20
Nope, no update. I'm currently not working on this project and I won't until they release their announced "big .NET update this summer.".

**Comment by St0l3nID** [comment] 2024-10-12 03:56
Heyo, i barley had connection issues in the past and since i updated to newest Loupedeck version i'm dealing with constant issues of the HA-Buttons not working anymore.
(Loupedeck on 6.0.0.20753 and plugin on 0.8)
I'm aware you tried a fix for this in 0.8, but wanted to give you some feedback that, for me, it now work less stable then before.
Thanks for your efforts :)

**Comment by schmic** [comment] 2024-10-12 11:06
Hello @St0l3nID ... could you please explain why you think there are connection problems or loose of connection? Are button presses for switches or lights not going to HA? Do they on the 2nd or 3rd try? Please explain a bit more how you experience the issues so I am able to narrow it down.

Please have a look at the logfile, probably attach it here, and check if there are any errors or messages. The readme explains where you can find the log for the new 6.0 version.

**Comment by St0l3nID** [comment] 2024-10-12 11:51
[Ha.log](https://github.com/user-attachments/files/17349851/Ha.log)
Sure, the log seems to call the actions, as far as i can tell it is perfectly connected in the beginning, however afer a while the buttons dont trigger the options of HA.
As you can see in the logs i try to switch lights in my kitchen (kuechenlicht_licht) and toggle scenes in my living room, but HA does simply not respond.
Unfortunatly in this log i didnt interact until it didnt work already.

Restarting loupedeck makes it work again, i cant further nail it down as to why it breaks though.
But once its broken the scene toggles and light  toggles dont work anymore and the light state is not reflected on the buttons anymore either.

**Comment by schmic** [comment] 2024-10-12 11:57
Okay, there are definitely some reconnects in your log @St0l3nID ...

I'll see how this compares and behaves to mine. There is a new websocket client involved now and I think it behaves different to the old one.

**Comment by St0l3nID** [comment] 2024-10-12 12:26
i figured it out, its something within ha itself that seems to break it,  here is a video of me exploring it:
https://youtu.be/mdERYm2MBfI

Plus the log (for the second automation i trigger)

[Ha.log](https://github.com/user-attachments/files/17350005/Ha.log)

**Comment by schmic** [comment] 2024-10-12 14:44
> edit: Seems like specificly Scene:Create is killing it.

I think I can reproduce it, though I have no explanation what's happening or why ...

btw. you have a new follower 👀

**Comment by schmic** [comment] 2024-10-12 15:49
Fixed by 0.8.1 - thanks for reporting and debugging.

**Closed by schmic** 2024-10-12 15:49 UTC
Labels: bug

**Comment by St0l3nID** [comment] 2024-10-12 16:34
Can confirm it worked^^

Thanks for the effort and the follow 👍
